name: signal_perfect
dependencies:
  - python
  - pip
  - pip:
      - mkdocs
      - mkdocs-material
      - nbformat
      - numpy
      - pandas
      - plotly
      - pytest
      - pytest-benchmark
      - scipy
